### ISSUE TITLE
Change the font Color and Reduce the font Size

### ISSUE THREAD

**Issue by Eshwar5799** [Eshwar5799/Image_Gallery#1]

**Comment by imarchit19** [comment]
Please assign it to me.

**Comment by waridrox** [comment]
Working on it !!!

**Comment by Eshwar5799** [comment]
@waridrox  @imarchit19  is  already working on it !! I will assign you another issue , Don't worry

**Comment by waridrox** [comment]
@Eshwar5799 Ok, do let me know what more enhancements can be made ! Btw, I am a newbie in web dev so was eager to contribute to your project
